name: Fetch Natalie News and Post to Slack

on:
  schedule:
    - cron: '00 10 * * *' # JST 19:00 に実行 (UTC 10:00)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Go のセットアップ
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # 適切なバージョンを指定

      - name: 環境変数の設定
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          echo "SLACK_TOKEN and CHANNEL_ID are set"

      - name: スクリプトの実行
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: go run main.go
