name: Fetch Natalie News and Post to Slack

on:
  schedule:
    - cron: '00 10 * * *' # JST 19:00 に実行 (UTC 10:00)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: [デバッグ] YAML 読み込み確認
        run: echo "✅ This is the latest version of YAML"

      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Go のセットアップ
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0

      - name: 環境変数のデバッグ
        run: |
          echo "SLACK_TOKEN length: ${#SLACK_TOKEN}"
          echo "CHANNEL_ID length: ${#CHANNEL_ID}"
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}