name: Fetch Natalie News and Post to Slack

on:
  schedule:
    - cron: '00 10 * * *' # JST 19:00 に実行 (UTC 10:00)
  workflow_dispatch:

jobs:
  scrape_and_post:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: タイムゾーンの設定
        run: echo "TZ=Asia/Tokyo" >> $GITHUB_ENV

      - name: Go のセットアップ
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: 依存関係の取得
        run: go mod download

      - name: スクリプトの実行
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: go run main.go